{% set name = "treetop" %}
{% set version = "1.6.18" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: a3043f32f1c652aa2abdf3a3848edb2d2f69897257af2675516ac61355c183da

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - rb-polyglot >=0.3,<0.4
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/treetop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Parsing Expression Grammar (PEG) Parser generator DSL for Ruby
  doc_url: http://www.rubydoc.info/gems/treetop
  dev_url: https://github.com/cjheath/treetop

extra:
  recipe-maintainers:
    - jdmarques
